export const ROUTES = {
  HOME: '/',
  PRODUCTS: '/products',
  PRODUCT_DETAIL: '/products/:id',
  CART: '/cart',
  CHECKOUT: '/checkout',
  ORDER_SUCCESS: '/order-success',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  PROFILE: '/profile',
  ORDERS: '/orders',
  WISHLIST: '/wishlist',
  STORES: '/stores',
  TRACK_ORDER: '/track-order',
  PROMOTIONS: '/promotions',
  ADMIN: '/admin',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_PRODUCT_ADD: '/admin/products/add',
  ADMIN_PRODUCT_EDIT: '/admin/products/edit/:id',
  ADMIN_CATEGORIES: '/admin/categories',
  ADMIN_ORDERS: '/admin/orders',
  ADMIN_ORDER_DETAIL: '/admin/orders/:id',
  ADMIN_USERS: '/admin/users',
  ADMIN_PROMOTIONS: '/admin/promotions',
  ADMIN_BANNERS: '/admin/banners',
  ADMIN_REVIEWS: '/admin/reviews',
  ADMIN_SETTINGS: '/admin/settings',
};

export const ADMIN_NAV = [
  { path: '/admin/dashboard', label: 'Dashboard', icon: 'LayoutDashboard' },
  { path: '/admin/products', label: 'San pham', icon: 'Package' },
  { path: '/admin/categories', label: 'Danh muc', icon: 'FolderTree' },
  { path: '/admin/orders', label: 'Don hang', icon: 'ShoppingBag' },
  { path: '/admin/users', label: 'Nguoi dung', icon: 'Users' },
  { path: '/admin/promotions', label: 'Khuyen mai', icon: 'Ticket' },
  { path: '/admin/banners', label: 'Banner', icon: 'Image' },
  { path: '/admin/reviews', label: 'Danh gia', icon: 'Star' },
  { path: '/admin/settings', label: 'Cai dat', icon: 'Settings' },
];
